version: "3.7"

services:
  docusaurus:
    volumes:
      - ./../docusaurus:/app/website

    ports:
      - 3000:3000/tcp
      - 35729:35729/tcp
    image: docusaurus
    command: bash -c 'yarn install && yarn start'
